local converters = require("nvim-highlight-colors.color.converters")
local assert = require("luassert")

describe('Converters', function()
	it('should convert rgb to hex', function()
		local hex_value = converters.rgb_to_hex(255, 255, 255)
		assert.are.equal(hex_value, '#FFFFFF')
	end)

	it('should convert hex to rgb', function()
		local rgb_table = converters.hex_to_rgb('#FFFFFF')
		assert.are.equal(rgb_table[1], 255)
		assert.are.equal(rgb_table[2], 255)
		assert.are.equal(rgb_table[3], 255)
	end)

	it('should convert short hex to rgb', function()
		local rgb_table = converters.hex_to_rgb('#FFF')
		assert.are.equal(rgb_table[1], 255)
		assert.are.equal(rgb_table[2], 255)
		assert.are.equal(rgb_table[3], 255)
	end)

	it('should return nil for invalid hex', function()
		local rgb_table = converters.hex_to_rgb('#FLK')
		assert.is_nil(rgb_table)
	end)

	it('should convert short hex to hex', function()
		local hex_value = converters.short_hex_to_hex('#FFF')
		assert.are.equal(hex_value, '#FFFFFF')
	end)

	it('should convert hsl to rgb', function()
		local hsl_table = converters.hsl_to_rgb(240, 100, 68)
		assert.are.equal(hsl_table[1], 91)
		assert.are.equal(hsl_table[2], 91)
		assert.are.equal(hsl_table[3], 255)
		assert.are.equal(hsl_table[4], 255)
	end)

	it('should convert oklch to rgb', function()
		-- oklch(1 0 0) is white (or very close to it)
		local rgb_table = converters.oklch_to_rgb(1, 0, 0)
		-- Allow tolerance of ±2 for rounding errors
		assert.is_true(rgb_table[1] >= 253 and rgb_table[1] <= 255)
		assert.is_true(rgb_table[2] >= 253 and rgb_table[2] <= 255)
		assert.is_true(rgb_table[3] >= 253 and rgb_table[3] <= 255)
		assert.are.equal(rgb_table[4], 255)
	end)

	it('should convert oklch to rgb for color values', function()
		-- oklch(0.628 0.225 328.4) is a pink/magenta color
		local rgb_table = converters.oklch_to_rgb(0.628, 0.225, 328.4)
		-- Allow some tolerance in the conversion (±10)
		assert.is_true(rgb_table[1] >= 194 and rgb_table[1] <= 214)
		assert.is_true(rgb_table[2] >= 59 and rgb_table[2] <= 79)
		assert.is_true(rgb_table[3] >= 192 and rgb_table[3] <= 212)
	end)
end)
